### ISSUE TITLE
Exception On Business Registration

### ISSUE THREAD

**Issue by josevh** [alariva/timegrid#12]
When visiting 
```
/manager/business/create
```
```
InvalidArgumentException in Reader.php line 46:
The file "/home/overthinkingme/Applications/timegrid/storage/app/geoip.mmdb" does not exist or is not readable.
```

Controller: Manager/BusinessController
Line 50:
```
$location = GeoIP::getLocation();
```

Not sure how you plan to implement it, just thought I'd submit the bug to document it.

**Comment by josevh** [comment]
Fixed by running 
```
php artisan geoip:update
```
from instructions on https://github.com/Torann/laravel-geoip

I'll try a fresh install tomorrow and see if I can reproduce it.
It might have been a faulty install on my end.

**Comment by alariva** [comment]
Thank you, now I notice this is missing in the instllarion instructions. Will add it later today.

**Comment by alariva** [comment]
Added [task for documentation](https://trello.com/c/564c2203db1a64bd9d3c16c8)

**Comment by alariva** [comment]
Installation Steps added with 2ac0cde6b1b0937d587ac0e383187d1aa142b55f
