### ISSUE TITLE
Missing translation keys

### ISSUE THREAD

**Issue by alariva** [alariva/timegrid#13]
Many validation alert messages are missing

Validations:

  * `/user/business/X/contact/create`
    * `validation.min.string`

Other:

  * `/manager/business/X`
    * `Preferences.App\Business.appointment Code Length.label`

**Comment by josevh** [comment]
Setting custom validation message can be done by using the ```oninvalid``` html attribute.

From user\contacts\_form.blade.php:
```
{!! Form::text('firstname', \Auth::user()->name,
                array('required',
                      'class'=>'form-control',
                      'placeholder'=> trans('manager.contacts.form.firstname.label'),
                      'oninvalid' => 'this.setCustomValidity("{{ the.english.translation }}")' )) !!}
```


Did you want a standard message for all, "this is a required field", or custom messages depending on the field?

Also, where should the translations be stored? user.php?

**Comment by alariva** [comment]
Thank you.

The first and quick approach was to have at least a validation message :dancer: 

Now it sounds a good idea to provide a field-specific message. For this case the translation key would fit in **user.php** and I'm trying to bring some [translation guidelines here](https://github.com/alariva/timegrid/wiki/Translations)

**Comment by josevh** [comment]
I placed the validation text where the placeholder text was sourced since the page did not use any translation for User.php. Any opinions on this implementation? I'm still learning your organization structure.

Also, where do you stand on 'tu' vs 'su' for Spanish translations?

**Comment by alariva** [comment]
Your approach seems correct.

Regarding the spanish use, this is almost an **es_ES** vs **es_AR** specific discussion and we can talk about it on [chat](https://timegrid.slack.com/messages/i18n/).

**Comment by alariva** [comment]
Most validation and common strings can be taken from [caouecs/Laravel-lang](https://github.com/caouecs/Laravel-lang)

**Comment by alariva** [comment]
Added all the default validation keys 6ac24b7d52dfc2d7fc146726f2fac07ffab5d117
