### ISSUE TITLE
Business preferences updating delayed

### ISSUE THREAD

**Issue by josevh** [alariva/timegrid#19]
visit ``` /manager/business/{$id}/preferences ```
and update a setting.

Redirected to ``` /manager/business/{$id}/ ```
Visiting ``` /manager/business/{$id}/preferences ``` again shows old preferences for up to a minute.

```dd($preferences)``` on the ```getPreferences()``` method of ```BusinessController``` shows that the values are updated but that is not reflected in form immediately.

**Comment by alariva** [comment]
What you state is correct and it is related to the cache, [remember method](https://github.com/alariva/timegrid/blob/development/app/Preference.php#L39)

So far I have not found any workaround for this, so remains open to fix or even enhance the whole config/preferences solution approach.

Probably for `>v3.5.x`

**Comment by alariva** [comment]
Caching was disabled.

To be re-implemented some other way around.
