### ISSUE TITLE
Post-Login redirect to intended

### ISSUE THREAD

**Issue by alariva** [alariva/timegrid#3]
When a user is entering a specific URL as guest (no login), the post-login event should redirect back to this requested URL.

__Example:__

1. Guest user enters `timegrid.io/testalias`
2. Guest is requested to login
3. Guest performs login (only **oAuth** process is affected)
4. Identified user should be now redirected to `timegrid.io/testalias`

This is not actually happening, the user is being redirected to default `timegrid.io/` home.

**Comment by josevh** [comment]
This is occurring only when authenticating via oAuth?

**Comment by alariva** [comment]
Yes, see that there are two controllers.

I believe the issue is given [here](https://github.com/alariva/timegrid/blob/development/app/Http/Controllers/Auth/OAuthController.php#L39)

You can find a bit further info in this [Trello Card](https://trello.com/c/mtV44ODH/10-redirect-original-after-login)

**Comment by alariva** [comment]
Thank you for [this commit](https://github.com/josevh/timegrid/commit/c58dbc4ef47d65b9c023ccdb53b5c8c89a65eb9b), I will check it. But I believe the redirect is already working with standard authentication and the bug is only given with **oAuth**.

**Comment by josevh** [comment]
@alariva Yeah, I deleted the branch after I realized. Sorry.
