### ISSUE TITLE
TYPO: Subscriptions

### ISSUE THREAD

**Issue by josevh** [alariva/timegrid#33]
The typo ```suscriptions``` is found URLs and in site text.
Correct spelling should be ```subscriptions``` in English.

Don't know if you'd like to fix route and user-visible text only or fix filenames as well.

**Comment by alariva** [comment]
Yes, we should fix them all. Thanks for the finding.

**Comment by alariva** [comment]
https://github.com/alariva/timegrid/commit/86e0b4fe0ebf3d1f1f48672b3acccb0259f97b15
