### ISSUE TITLE
Entering 1 char in new user name/username fields gives password advice

### ISSUE THREAD

**Issue by bcooney** [alariva/timegrid#45]
As above, entering any 1 character into the new user NAME and USERNAME fields gives advice about the password standards of the site. Screenshot attached.
<img width="800" alt="timegrid_io_1" src="https://cloud.githubusercontent.com/assets/7929717/11605995/319039e6-9b4b-11e5-95ab-75e3e933fb4a.png">

Browser: Firefox 42
OS: OS X 10.10.5
Location: China

**Comment by alariva** [comment]
Thanks for the report, again. This will get fixed. Are you wishing to make a PR? In that case let me know.
